### ISSUE TITLE
Integration with xscreensaver

### ISSUE THREAD

**Issue by shellshock1953** [st3w/neo#13]
It will be **SUPER** cool to integrate `neo` with [xscreensaver](https://www.jwz.org/xscreensaver/)! Is there any possibility to achieve this?
Its already has `gl-matix` - but `neo` feels way more "natural".
Thanks!

**Comment by schmitmd** [comment]
I think Wayland support with something like [swaylock](https://github.com/swaywm/swaylock) would also be very cool.  I have no idea where to even start looking for how to help make this happen though.  afaict, neo functions only within a terminal via curses.  I think swaylock only supports images for the background..

**Comment by st3w** [comment]
This would require a complete rewrite in a different framework, which is way beyond the original scope.
